<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Sc2Xboxed.Osk</AssemblyName>
    <RootNamespace>Sc2Xboxed.Osk</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sc2Xboxed.Core\Sc2Xboxed.Core.csproj" />
    <ProjectReference Include="..\Sc2Xboxed.Hid\Sc2Xboxed.Hid.csproj" />
  </ItemGroup>

</Project>
